Repository php-fig/per-coding-style, pull requests merged in 2022-07, with the labels that each got.

#5 Add section describing nowdoc and heredoc
  spec.md
Labels: enhancement, core

#17 Add a section on short-lambdas
  spec.md
Labels: enhancement

#18 Add a section on trailing commas
  spec.md
Labels: enhancement

#19 Update the abstract/final section to cover all modifier keywords
  spec.md
Labels: enhancement

#7 Add section on enumerations.
  spec.md
Labels: enhancement, core

#16 Add method chaining style specification
  spec.md
Labels: enhancement, optional
